# Generated by Django 4.1.1 on 2022-09-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarangpur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='date',
            new_name='pub_date',
        ),
    ]
