# Generated by Django 4.1.1 on 2022-09-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarangpur', '0002_rename_date_slider_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slider')),
                ('altText', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('about', models.TextField()),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
