# Generated by Django 4.1.1 on 2022-09-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarangpur', '0003_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='slider')),
                ('designation', models.CharField(choices=[('Mukhiya', 'Mukhiya'), ('Up Mukhiya', 'Up Mukhiya'), ('Sarpanch', 'Sarpanch'), ('Up Sarpanch', 'Up Sarpanch'), ('Panchayat Samiti', 'Panchayat Samiti'), ('Ward Member', 'Ward Member')], max_length=50)),
                ('about', models.TextField(blank=True)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
