# Generated by Django 4.1.1 on 2022-09-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarangpur', '0004_authorities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latestnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='news')),
                ('link', models.URLField(null=True)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
