# Generated by Django 4.1.1 on 2022-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarangpur', '0005_latestnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='link',
            field=models.URLField(blank=True, default='/'),
        ),
    ]
